version: '3.8'

services:
  fastapi_app:
    build: .
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - "${DOCKER_DIRECTORY_MOUNT}:/resumenes"  # Montaje de PDF
    env_file:
      - .env
    command: >
      sh -c "pip install debugpy &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/app"